"use client";
import React from 'react'
import ReactDOM from 'react-dom'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Header } from './components/Header'
import './globals.css'
import { Provider } from 'react-redux'
import { store } from './store'

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Header /> */}
        <Provider store={store}>
        {children}
        </Provider>
      </body>
    </html>
  )
}